// schedule.js — Switchable weekly Schedule Profiles (Roadmap-adjacent,
// built on request). Multiple named weekly templates — "Regular" today,
// something like "Professional" later — with an easy switcher between
// them, rather than one hardcoded week.
//
// Any profile can also define an ALTERNATE version of specific days
// (e.g. Regular's Monday/Wednesday differ on job weeks) via a simple
// anchor-date + interval rule, with a manual override — deliberately not
// a silent-forever recurrence, since term/holiday dates can't be known
// in advance and a rule that quietly drifts wrong the first time a
// school break breaks the week-numbering is worse than no automation at
// all (the same reasoning already used when the original timetable was
// built as 4 dated weeks rather than an open-ended rule).
//
// The seed data below (SCHEDULE_SEED_REGULAR) was generated by parsing
// the actual validated 688-event .ics file directly — not retyped by
// hand from the planning doc — and cross-checked that every non-Monday/
// Wednesday day is byte-identical across all 4 weeks before being
// treated as a reusable template, so the two sources can't have quietly
// drifted apart from each other.

const SCHEDULE_SEED_REGULAR = {
  name: "Regular",
  days: {
    sun: [
      {s:"04:30",e:"04:35",t:"Wake, bathroom",d:""},
      {s:"04:35",e:"04:50",t:"Eye exercises",d:""},
      {s:"04:50",e:"05:00",t:"Light stretching only",d:"Optional, not the full protocol"},
      {s:"05:00",e:"05:15",t:"Breakfast",d:""},
      {s:"05:15",e:"06:05",t:"Study \u2014 Canvas/OneNote backlog",d:""},
      {s:"06:05",e:"06:15",t:"Break",d:""},
      {s:"06:15",e:"07:05",t:"Study \u2014 backlog (cont.) or flex",d:""},
      {s:"07:05",e:"07:15",t:"Break",d:""},
      {s:"07:15",e:"08:05",t:"Chess",d:"Puzzles + review"},
      {s:"08:05",e:"08:15",t:"Break",d:""},
      {s:"08:15",e:"09:05",t:"Language immersion",d:""},
      {s:"09:05",e:"09:15",t:"Break",d:""},
      {s:"09:15",e:"10:05",t:"Flex slot \u2014 Coding/Roblox",d:""},
      {s:"10:05",e:"11:00",t:"Family/errands/free",d:""},
      {s:"11:00",e:"12:00",t:"Lunch + family",d:""},
      {s:"12:00",e:"14:00",t:"Park / outdoor / social",d:"Long, protected"},
      {s:"14:00",e:"14:50",t:"AI automation / Google skills",d:"Alternate weeks"},
      {s:"14:50",e:"15:00",t:"Break",d:""},
      {s:"15:00",e:"15:40",t:"NGO and Sons \u2014 weekly maintenance",d:"Once Phase 1 backlog clear"},
      {s:"15:40",e:"16:30",t:"Aim training",d:"2nd weekly session"},
      {s:"16:30",e:"18:30",t:"Free/flex/rest",d:"Protected"},
      {s:"18:30",e:"19:15",t:"Dinner + family",d:""},
      {s:"19:15",e:"21:00",t:"Free/rest",d:""},
      {s:"21:00",e:"22:00",t:"Wind down/buffer",d:""}
    ],
    mon: [
      {s:"04:30",e:"04:35",t:"Bathroom",d:"Quick wash-up \u2014 hydration/stretch folded into warmup, not separate"},
      {s:"04:35",e:"04:50",t:"Eye exercises",d:"15 min, every morning before workout"},
      {s:"04:50",e:"05:20",t:"Workout \u2014 Nerve/flex",d:""},
      {s:"05:20",e:"05:45",t:"Workout \u2014 Core (full)",d:""},
      {s:"05:45",e:"05:55",t:"Workout \u2014 GAD",d:""},
      {s:"05:55",e:"06:15",t:"Workout \u2014 TKD/MMA/Kenjutsu",d:""},
      {s:"06:15",e:"06:35",t:"Workout \u2014 Push strength",d:"Phase 1 bodyweight, per Plan v3 doc"},
      {s:"06:35",e:"06:50",t:"Shower",d:""},
      {s:"06:50",e:"07:05",t:"Breakfast",d:""},
      {s:"07:05",e:"08:05",t:"Study \u2014 Canvas/OneNote backlog",d:"Phase 1: most overdue Canvas/OneNote item. Phase 2 (once backlog clear): see mapping in timetable doc."},
      {s:"08:05",e:"08:15",t:"Get ready",d:"Pack bag"},
      {s:"08:15",e:"08:40",t:"Travel to school",d:""},
      {s:"08:40",e:"14:50",t:"School",d:""},
      {s:"15:05",e:"15:20",t:"Snack/change",d:""},
      {s:"15:20",e:"16:55",t:"Evening routine \u2014 Cricket + run + cooldown",d:"Cricket 35 + run 45 + cooldown 15"},
      {s:"16:55",e:"17:10",t:"Shower",d:""},
      {s:"17:10",e:"18:00",t:"Coding \u2014 31-Day Plan (Python)",d:""},
      {s:"18:00",e:"18:10",t:"Break",d:""},
      {s:"18:10",e:"18:50",t:"Dinner + family",d:""},
      {s:"18:50",e:"19:05",t:"Park",d:""},
      {s:"19:05",e:"19:50",t:"Chess",d:"Puzzles + tactics + opening prep"},
      {s:"19:50",e:"20:00",t:"Break",d:""},
      {s:"20:00",e:"20:35",t:"Business \u2014 Sydney Web Studio",d:""},
      {s:"20:35",e:"20:50",t:"Language \u2014 Tamil/Gujarati (Ling)",d:""},
      {s:"20:50",e:"21:30",t:"Free/flex",d:""},
      {s:"21:30",e:"22:00",t:"Wind down",d:""}
    ],
    tue: [
      {s:"04:30",e:"04:35",t:"Bathroom",d:"Quick wash-up \u2014 hydration/stretch folded into warmup, not separate"},
      {s:"04:35",e:"04:50",t:"Eye exercises",d:"15 min, every morning before workout"},
      {s:"04:50",e:"05:20",t:"Workout \u2014 Nerve/flex",d:""},
      {s:"05:20",e:"05:35",t:"Workout \u2014 Core (light)",d:""},
      {s:"05:35",e:"05:45",t:"Workout \u2014 GAD",d:""},
      {s:"05:45",e:"06:05",t:"Workout \u2014 TKD/MMA/Kenjutsu",d:""},
      {s:"06:05",e:"06:35",t:"Workout \u2014 Vert session",d:""},
      {s:"06:35",e:"06:50",t:"Shower",d:""},
      {s:"06:50",e:"07:05",t:"Breakfast",d:""},
      {s:"07:05",e:"08:05",t:"Study \u2014 Canvas/OneNote backlog",d:"Phase 1: most overdue Canvas/OneNote item. Phase 2 (once backlog clear): see mapping in timetable doc."},
      {s:"08:05",e:"08:15",t:"Get ready",d:"Pack bag"},
      {s:"08:15",e:"08:40",t:"Travel to school",d:""},
      {s:"08:40",e:"14:20",t:"School",d:"Shorter day \u2014 ends 2:20pm"},
      {s:"14:35",e:"14:50",t:"Snack/change",d:""},
      {s:"14:50",e:"16:25",t:"Evening routine \u2014 Basketball + intervals + cooldown",d:"Basketball 35 + interval run 45 + cooldown 15"},
      {s:"16:25",e:"16:40",t:"Shower",d:""},
      {s:"16:40",e:"17:30",t:"Coding \u2014 security-adjacent day",d:""},
      {s:"17:30",e:"17:40",t:"Break",d:""},
      {s:"17:40",e:"18:20",t:"Dinner + family",d:""},
      {s:"18:20",e:"18:35",t:"Park",d:""},
      {s:"18:35",e:"19:20",t:"Chess",d:""},
      {s:"19:20",e:"19:30",t:"Break",d:""},
      {s:"19:30",e:"20:05",t:"Business \u2014 Sydney Web Studio",d:""},
      {s:"20:05",e:"20:20",t:"Language",d:""},
      {s:"20:20",e:"21:15",t:"Free/flex",d:"Extra \u2014 shorter school day"},
      {s:"21:15",e:"22:00",t:"Wind down",d:""}
    ],
    wed: [
      {s:"04:30",e:"04:35",t:"Bathroom",d:"Quick wash-up \u2014 hydration/stretch folded into warmup, not separate"},
      {s:"04:35",e:"04:50",t:"Eye exercises",d:"15 min, every morning before workout"},
      {s:"04:50",e:"05:20",t:"Workout \u2014 Nerve/flex",d:""},
      {s:"05:20",e:"05:45",t:"Workout \u2014 Core (full)",d:""},
      {s:"05:45",e:"05:55",t:"Workout \u2014 GAD",d:""},
      {s:"05:55",e:"06:15",t:"Workout \u2014 TKD/MMA/Kenjutsu",d:""},
      {s:"06:15",e:"06:35",t:"Workout \u2014 Pull strength",d:"Phase 1 bodyweight, per Plan v3 doc"},
      {s:"06:35",e:"06:50",t:"Shower",d:""},
      {s:"06:50",e:"07:05",t:"Breakfast",d:""},
      {s:"07:05",e:"08:05",t:"Study \u2014 Canvas/OneNote backlog",d:"Phase 1: most overdue Canvas/OneNote item. Phase 2 (once backlog clear): see mapping in timetable doc."},
      {s:"08:05",e:"08:15",t:"Get ready",d:"Pack bag"},
      {s:"08:15",e:"08:40",t:"Travel to school",d:""},
      {s:"08:40",e:"14:50",t:"School",d:""},
      {s:"15:05",e:"15:20",t:"Snack/change",d:""},
      {s:"15:20",e:"16:55",t:"Evening routine \u2014 Cricket/Soccer + tempo run + cooldown",d:""},
      {s:"16:55",e:"17:10",t:"Shower",d:""},
      {s:"17:10",e:"18:00",t:"Coding \u2014 31-Day Plan (Python)",d:""},
      {s:"18:00",e:"18:10",t:"Break",d:""},
      {s:"18:10",e:"18:50",t:"Dinner + family",d:""},
      {s:"18:50",e:"19:05",t:"Park",d:""},
      {s:"19:05",e:"19:50",t:"Chess",d:""},
      {s:"19:50",e:"20:00",t:"Break",d:""},
      {s:"20:00",e:"20:35",t:"AI automation",d:""},
      {s:"20:35",e:"20:50",t:"Language",d:""},
      {s:"20:50",e:"21:30",t:"Free/flex",d:""},
      {s:"21:30",e:"22:00",t:"Wind down",d:""}
    ],
    thu: [
      {s:"04:30",e:"04:35",t:"Bathroom",d:"Quick wash-up \u2014 hydration/stretch folded into warmup, not separate"},
      {s:"04:35",e:"04:50",t:"Eye exercises",d:"15 min, every morning before workout"},
      {s:"04:50",e:"05:20",t:"Workout \u2014 Nerve/flex",d:""},
      {s:"05:20",e:"05:35",t:"Workout \u2014 Core (light)",d:""},
      {s:"05:35",e:"05:45",t:"Workout \u2014 GAD",d:""},
      {s:"05:45",e:"06:05",t:"Workout \u2014 TKD/MMA/Kenjutsu",d:""},
      {s:"06:05",e:"06:40",t:"Workout \u2014 Leg day",d:"Phase 1, Thursday"},
      {s:"06:40",e:"07:00",t:"Workout \u2014 Vert session",d:""},
      {s:"07:00",e:"07:15",t:"Shower",d:""},
      {s:"07:15",e:"07:30",t:"Breakfast",d:""},
      {s:"07:30",e:"08:05",t:"Study \u2014 Canvas/OneNote backlog",d:"Phase 1: most overdue Canvas/OneNote item. Phase 2 (once backlog clear): see mapping in timetable doc. (shorter day)"},
      {s:"08:05",e:"08:15",t:"Get ready",d:"Pack bag"},
      {s:"08:15",e:"08:40",t:"Travel to school",d:""},
      {s:"08:40",e:"14:50",t:"School",d:""},
      {s:"14:50",e:"16:30",t:"Transit chain to tuition",d:"Bike home fast, change, bus, train to Parramatta"},
      {s:"16:30",e:"18:30",t:"Tuition",d:"Parramatta"},
      {s:"18:30",e:"19:15",t:"Return transit",d:"Estimate \u2014 confirm real time"},
      {s:"19:15",e:"19:25",t:"Change into workout gear",d:""},
      {s:"19:25",e:"20:15",t:"Recovery run + cooldown",d:"35 min run + 15 cooldown"},
      {s:"20:15",e:"20:30",t:"Shower",d:""},
      {s:"20:30",e:"21:10",t:"Dinner + family",d:""},
      {s:"21:10",e:"21:40",t:"Catch-up \u2014 Coding/language/business",d:""},
      {s:"21:40",e:"22:00",t:"Wind down",d:""}
    ],
    fri: [
      {s:"04:30",e:"04:35",t:"Bathroom",d:"Quick wash-up \u2014 hydration/stretch folded into warmup, not separate"},
      {s:"04:35",e:"04:50",t:"Eye exercises",d:"15 min, every morning before workout"},
      {s:"04:50",e:"05:20",t:"Workout \u2014 Nerve/flex",d:""},
      {s:"05:20",e:"05:45",t:"Workout \u2014 Core (full)",d:""},
      {s:"05:45",e:"05:55",t:"Workout \u2014 GAD",d:""},
      {s:"05:55",e:"06:15",t:"Workout \u2014 TKD/MMA/Kenjutsu",d:""},
      {s:"06:15",e:"06:35",t:"Workout \u2014 Shoulder strength",d:"Phase 1 bodyweight, per Plan v3 doc"},
      {s:"06:35",e:"06:50",t:"Shower",d:""},
      {s:"06:50",e:"07:05",t:"Breakfast",d:""},
      {s:"07:05",e:"08:05",t:"Study \u2014 Canvas/OneNote backlog",d:"Phase 1: most overdue Canvas/OneNote item. Phase 2 (once backlog clear): see mapping in timetable doc."},
      {s:"08:05",e:"08:15",t:"Get ready",d:"Pack bag"},
      {s:"08:15",e:"08:40",t:"Travel to school",d:""},
      {s:"08:40",e:"14:50",t:"School",d:""},
      {s:"15:05",e:"15:20",t:"Snack/change",d:""},
      {s:"15:20",e:"16:55",t:"Evening routine \u2014 Basketball + sprints + cooldown",d:""},
      {s:"16:55",e:"17:10",t:"Shower",d:""},
      {s:"17:10",e:"18:00",t:"Coding \u2014 language rotation (C#/Lua)",d:""},
      {s:"18:00",e:"18:10",t:"Break",d:""},
      {s:"18:10",e:"18:50",t:"Dinner + family",d:""},
      {s:"18:50",e:"19:05",t:"Park",d:""},
      {s:"19:05",e:"19:50",t:"Chess",d:""},
      {s:"19:50",e:"20:00",t:"Break",d:""},
      {s:"20:00",e:"20:35",t:"Google skills",d:""},
      {s:"20:35",e:"20:50",t:"Language",d:""},
      {s:"20:50",e:"21:30",t:"Free/flex",d:""},
      {s:"21:30",e:"22:00",t:"Wind down",d:""}
    ],
    sat: [
      {s:"04:30",e:"04:35",t:"Wake, bathroom",d:""},
      {s:"04:35",e:"04:50",t:"Eye exercises",d:""},
      {s:"04:50",e:"07:50",t:"Morning athletic block (3 hrs)",d:"Nerve/flex, core, GAD, TKD full practice+sparring, soccer skills, vert+measure"},
      {s:"07:50",e:"08:05",t:"Breakfast/shower",d:""},
      {s:"08:05",e:"08:55",t:"Study \u2014 Canvas/OneNote backlog",d:""},
      {s:"08:55",e:"09:05",t:"Break",d:""},
      {s:"09:05",e:"09:55",t:"NGO and Sons maths",d:"Phase 1 intensive catch-up"},
      {s:"09:55",e:"10:05",t:"Break",d:""},
      {s:"10:05",e:"10:55",t:"Coding \u2014 31-Day Plan",d:""},
      {s:"10:55",e:"11:05",t:"Break",d:""},
      {s:"11:05",e:"11:55",t:"Roblox dev w/ Eon",d:"Live co-working session"},
      {s:"11:55",e:"12:05",t:"Break",d:""},
      {s:"12:05",e:"13:05",t:"Business \u2014 Sydney Web Studio",d:""},
      {s:"13:05",e:"14:05",t:"Lunch + family/free",d:""},
      {s:"14:05",e:"14:55",t:"Chess",d:"Long games + engine review"},
      {s:"14:55",e:"15:05",t:"Break",d:""},
      {s:"15:05",e:"15:45",t:"Aim training",d:"Aiming.Pro"},
      {s:"15:45",e:"16:05",t:"Transition/free",d:""},
      {s:"16:05",e:"17:05",t:"Evening routine \u2014 6km long run + cooldown",d:"Sport already done this morning"},
      {s:"17:05",e:"17:25",t:"Shower/reset",d:""},
      {s:"17:25",e:"18:25",t:"Free/flex/social",d:""},
      {s:"18:25",e:"19:05",t:"Dinner + family",d:""},
      {s:"19:05",e:"19:50",t:"Language immersion",d:""},
      {s:"19:50",e:"21:00",t:"Free/flex/social",d:""},
      {s:"21:00",e:"22:00",t:"Wind down/buffer",d:""}
    ],
  },
  altDays: {
    mon: [
      {s:"04:30",e:"04:35",t:"Bathroom",d:"Quick wash-up \u2014 hydration/stretch folded into warmup, not separate"},
      {s:"04:35",e:"04:50",t:"Eye exercises",d:"15 min, every morning before workout"},
      {s:"04:50",e:"05:20",t:"Workout \u2014 Nerve/flex",d:""},
      {s:"05:20",e:"05:45",t:"Workout \u2014 Core (full)",d:""},
      {s:"05:45",e:"05:55",t:"Workout \u2014 GAD",d:""},
      {s:"05:55",e:"06:15",t:"Workout \u2014 TKD/MMA/Kenjutsu",d:""},
      {s:"06:15",e:"06:35",t:"Workout \u2014 Push strength",d:"Phase 1 bodyweight, per Plan v3 doc"},
      {s:"06:35",e:"06:50",t:"Shower",d:""},
      {s:"06:50",e:"07:05",t:"Breakfast",d:""},
      {s:"07:05",e:"08:05",t:"Study \u2014 Canvas/OneNote backlog",d:"Phase 1: most overdue Canvas/OneNote item. Phase 2 (once backlog clear): see mapping in timetable doc."},
      {s:"08:05",e:"08:15",t:"Get ready",d:"Pack bag"},
      {s:"08:15",e:"08:40",t:"Travel to school",d:""},
      {s:"08:40",e:"14:50",t:"School",d:""},
      {s:"15:05",e:"15:20",t:"Snack",d:""},
      {s:"15:20",e:"16:10",t:"Coding \u2014 31-Day Plan (catch-up)",d:"Pre-job window; routine already done this morning"},
      {s:"16:10",e:"18:15",t:"Marking job",d:""},
      {s:"18:15",e:"18:30",t:"Change into workout gear",d:""},
      {s:"18:30",e:"20:05",t:"Evening routine \u2014 Cricket + run + cooldown",d:"Full 95 min version, just later"},
      {s:"20:05",e:"20:20",t:"Shower",d:""},
      {s:"20:20",e:"21:00",t:"Dinner + family",d:""},
      {s:"21:00",e:"21:15",t:"Language",d:""},
      {s:"21:15",e:"21:45",t:"Business/rotating catch-up",d:""},
      {s:"21:45",e:"22:00",t:"Wind down",d:""}
    ],
    wed: [
      {s:"04:30",e:"04:35",t:"Bathroom",d:"Quick wash-up \u2014 hydration/stretch folded into warmup, not separate"},
      {s:"04:35",e:"04:50",t:"Eye exercises",d:"15 min, every morning before workout"},
      {s:"04:50",e:"05:20",t:"Workout \u2014 Nerve/flex",d:""},
      {s:"05:20",e:"05:45",t:"Workout \u2014 Core (full)",d:""},
      {s:"05:45",e:"05:55",t:"Workout \u2014 GAD",d:""},
      {s:"05:55",e:"06:15",t:"Workout \u2014 TKD/MMA/Kenjutsu",d:""},
      {s:"06:15",e:"06:35",t:"Workout \u2014 Pull strength",d:"Phase 1 bodyweight, per Plan v3 doc"},
      {s:"06:35",e:"06:50",t:"Shower",d:""},
      {s:"06:50",e:"07:05",t:"Breakfast",d:""},
      {s:"07:05",e:"08:05",t:"Study \u2014 Canvas/OneNote backlog",d:"Phase 1: most overdue Canvas/OneNote item. Phase 2 (once backlog clear): see mapping in timetable doc."},
      {s:"08:05",e:"08:15",t:"Get ready",d:"Pack bag"},
      {s:"08:15",e:"08:40",t:"Travel to school",d:""},
      {s:"08:40",e:"14:50",t:"School",d:""},
      {s:"15:05",e:"15:20",t:"Snack",d:""},
      {s:"15:20",e:"16:10",t:"Coding \u2014 31-Day Plan (catch-up)",d:""},
      {s:"16:10",e:"19:15",t:"Marking job",d:"Heavy day \u2014 confirmed 7:15pm return"},
      {s:"19:15",e:"19:25",t:"Change",d:""},
      {s:"19:25",e:"21:00",t:"Evening routine \u2014 Cricket/Soccer + tempo run + cooldown",d:"Full 95 min still fits"},
      {s:"21:00",e:"21:15",t:"Shower",d:""},
      {s:"21:15",e:"21:50",t:"Dinner + family",d:"Shortened"},
      {s:"21:50",e:"22:00",t:"Wind down",d:""}
    ],
  },
  altLabel: "Job week",
  altAnchorDate: "2026-08-17",
  altIntervalWeeks: 2,
  altWeekOverride: null,
};

const SCHEDULE_DAY_KEYS = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"];
const SCHEDULE_DAY_LABELS = { sun: "Sunday", mon: "Monday", tue: "Tuesday", wed: "Wednesday", thu: "Thursday", fri: "Friday", sat: "Saturday" };
const MASTER_V8_PHASES = [
  { id: "a", start: "2026-09-07", end: "2026-09-11", label: "Phase A · Wharton grind", focus: "Wharton is the first claim on every genuine flex block.", mode: "wharton" },
  { id: "b1", start: "2026-09-12", end: "2026-09-16", label: "Phase B1 · Clear bounded work", focus: "AM flex: tuition backlog. PM flex: tuition backlog and first-client outreach.", mode: "backlog" },
  { id: "b2", start: "2026-09-17", end: "2026-09-25", label: "Phase B2 · Trial practice", focus: "Trial competition practice takes the flexible work blocks.", mode: "trial" },
  { id: "c", start: "2026-09-26", end: "2026-12-04", label: "Phase C · Sustainable competition", focus: "Competition twice weekly, maths first until 20 October, then the normal study and venture rotation.", mode: "steady" },
];

const Schedule = {
  profiles: {},
  activeId: null,
  _viewDay: null,        // which day-of-week is shown in the editor tabs
  _editingIndex: null,   // index of the block currently being edited in the editor, or null
  _highlightTimer: null,
  _planDraft: [],

  buildMasterV8Profile() {
    const profile = structuredClone(SCHEDULE_SEED_REGULAR);
    profile.name = "Master Timetable v8";
    profile.masterVersion = 8;
    profile.phases = structuredClone(MASTER_V8_PHASES);
    profile.sourceNote = "Imported from shourya_master_timetable_v8.md";
    return profile;
  },

  async syncMasterV8({ activate = true, announce = true } = {}) {
    if (announce && this.profiles["master-v8"] && !confirm("Refresh the managed Master Timetable v8 profile? Any edits inside that profile will be replaced. Your other profiles and calendar entries will remain untouched.")) return;
    this.profiles["master-v8"] = this.buildMasterV8Profile();
    if (activate) this.activeId = "master-v8";
    await this.saveProfiles();
    if (activate) await chrome.storage.local.set({ hq_active_schedule_profile: this.activeId });
    this.renderProfileSelect();
    this.render();
    if (announce) Wallpaper?.toast?.("Master Timetable v8 synced. Your other profiles were kept.");
  },

  async init() {
    const s = await chrome.storage.local.get(["hq_schedule_profiles", "hq_active_schedule_profile", "hq_master_v8_activation_done", "hq_schedule_plan_undo_v1"]);
    this.profiles = s.hq_schedule_profiles || {};

    const shouldActivateMaster = !s.hq_master_v8_activation_done && (!s.hq_active_schedule_profile || s.hq_active_schedule_profile === "regular");
    if (!this.profiles["master-v8"] || this.profiles["master-v8"].masterVersion !== 8) {
      this.profiles["master-v8"] = this.buildMasterV8Profile();
      await this.saveProfiles();
    }

    this.activeId = shouldActivateMaster ? "master-v8" : (s.hq_active_schedule_profile && this.profiles[s.hq_active_schedule_profile])
      ? s.hq_active_schedule_profile
      : (Object.keys(this.profiles)[0] || null);
    if (shouldActivateMaster) await chrome.storage.local.set({ hq_active_schedule_profile: "master-v8", hq_master_v8_activation_done: true });

    this._viewDay = SCHEDULE_DAY_KEYS[new Date().getDay()];

    document.getElementById("schedule-profile-select").onchange = (e) => this.selectProfile(e.target.value);
    document.getElementById("schedule-add-profile-btn").onclick = () => this.addProfile();
    document.getElementById("schedule-import-master-btn").onclick = () => this.syncMasterV8();
    document.getElementById("schedule-rename-profile-btn").onclick = () => this.renameProfile();
    document.getElementById("schedule-delete-profile-btn").onclick = () => this.deleteProfile();
    document.getElementById("schedule-profile-editor").onsubmit = event => { event.preventDefault(); this.saveProfileEditor(); };
    document.getElementById("schedule-profile-cancel").onclick = () => this.closeProfileEditor();
    document.getElementById("schedule-week-override").onchange = (e) => this.setWeekOverride(e.target.value);
    document.getElementById("schedule-add-block-btn").onclick = () => this.startAddBlock();
    document.getElementById("schedule-start-blank-btn").onclick = () => this.createFirstProfile(false);
    document.getElementById("schedule-use-hq-template-btn").onclick = () => this.createFirstProfile(true);
    document.getElementById("schedule-plan-tasks-btn").onclick = () => this.buildTaskPlan();
    document.getElementById("schedule-apply-plan-btn").onclick = () => this.applyTaskPlan();
    document.getElementById("schedule-dismiss-plan-btn").onclick = () => this.dismissTaskPlan();
    document.getElementById("schedule-undo-plan-btn").onclick = () => this.undoTaskPlan();
    document.getElementById("schedule-undo-plan-btn").disabled = !s.hq_schedule_plan_undo_v1;
    document.getElementById("schedule-day-tabs").addEventListener("click", (e) => {
      const btn = e.target.closest(".schedule-day-tab");
      if (btn) { this._viewDay = btn.dataset.day; this._editingIndex = null; this.renderEditor(); }
    });

    this.renderProfileSelect();
    this.render();

    // The "current block" highlight in Today view depends on the clock,
    // not on any stored data — refresh it every minute without a full
    // re-render (re-render would also blow away in-progress edits).
    PageScheduler.register("schedule-highlight", 60000, () => this.renderTodayHighlightOnly());
  },

  async saveProfiles() {
    await chrome.storage.local.set({ hq_schedule_profiles: this.profiles });
  },

  get active() {
    return this.profiles[this.activeId];
  },

  // --- Alt-week logic ---

  mondayOf(date) {
    const d = new Date(date);
    const day = d.getDay(); // 0=Sun..6=Sat
    const diff = day === 0 ? -6 : 1 - day; // days to subtract to reach Monday
    d.setDate(d.getDate() + diff);
    d.setHours(0, 0, 0, 0);
    return d;
  },

  isAltWeek(profile, forDate) {
    if (profile.altWeekOverride === true) return true;
    if (profile.altWeekOverride === false) return false;
    if (!profile.altAnchorDate || !profile.altIntervalWeeks) return false;
    const anchorMonday = this.mondayOf(profile.altAnchorDate + "T00:00:00");
    const thisMonday = this.mondayOf(forDate || new Date());
    const weeksDiff = Math.round((thisMonday - anchorMonday) / (7 * 86400000));
    return weeksDiff >= 0 && weeksDiff % profile.altIntervalWeeks === 0;
  },

  activePhase(profile = this.active, forDate = new Date()) {
    if (!profile?.phases?.length) return null;
    const key = hqLocalDateKey(forDate);
    return profile.phases.find(phase => key >= phase.start && key <= phase.end) || null;
  },

  isFlexibleBlock(block) {
    return /flex|study|coding|business|catch-up|practice|competition/i.test(`${block?.t || ""} ${block?.d || ""}`);
  },

  phaseLabelForBlock(block, phase) {
    if (!phase || !this.isFlexibleBlock(block)) return null;
    if (phase.mode === "wharton") return "Wharton priority";
    if (phase.mode === "backlog") return Number(block.s?.slice(0, 2)) < 12 ? "Tuition backlog" : "Tuition backlog + client outreach";
    if (phase.mode === "trial") return "Competition trial practice";
    if (phase.mode === "steady") return "Competition / maths / study rotation";
    return null;
  },

  // The blocks actually in effect for a given day-of-week key right now,
  // accounting for the alt-week rule if this profile and day have one.
  blocksFor(profile, dayKey, forDate = new Date()) {
    const usesAlt = profile.altDays && profile.altDays[dayKey] && this.isAltWeek(profile, forDate);
    const base = usesAlt ? profile.altDays[dayKey] : (profile.days[dayKey] || []);
    const phase = this.activePhase(profile, forDate);
    return base.map(block => {
      const phasePriority = this.phaseLabelForBlock(block, phase);
      return phasePriority ? { ...block, phasePriority, d: [block.d, `v8 priority: ${phasePriority}`].filter(Boolean).join(" · ") } : block;
    });
  },

  dayHasAlt(profile, dayKey) {
    return !!(profile.altDays && profile.altDays[dayKey]);
  },

  // --- Profile management ---

  renderProfileSelect() {
    const sel = document.getElementById("schedule-profile-select");
    sel.innerHTML = Object.entries(this.profiles).map(([id, p]) =>
      `<option value="${id}" ${id === this.activeId ? "selected" : ""}>${escapeHtml(p.name)}</option>`
    ).join("") || '<option value="">No profile yet</option>';
    const hasProfile = !!this.active;
    document.getElementById("schedule-first-run").classList.toggle("hidden", hasProfile);
    document.getElementById("schedule-profile-select").disabled = !hasProfile;
    document.getElementById("schedule-rename-profile-btn").disabled = !hasProfile;
    document.getElementById("schedule-delete-profile-btn").disabled = !hasProfile;
    document.getElementById("schedule-add-block-btn").disabled = !hasProfile;
  },

  async createFirstProfile(usePrepared) {
    if (Object.keys(this.profiles).length) return;
    const blank = {
      name: "My Week",
      days: { sun: [], mon: [], tue: [], wed: [], thu: [], fri: [], sat: [] },
      altDays: {}, altLabel: "Alt week", altAnchorDate: null,
      altIntervalWeeks: 2, altWeekOverride: null,
    };
    this.profiles = { [usePrepared ? "regular" : "my-week"]: usePrepared ? structuredClone(SCHEDULE_SEED_REGULAR) : blank };
    this.activeId = Object.keys(this.profiles)[0];
    await this.saveProfiles();
    await chrome.storage.local.set({ hq_active_schedule_profile: this.activeId });
    this.renderProfileSelect();
    this.render();
    Wallpaper?.toast?.(usePrepared ? "Prepared HQ schedule imported." : "Blank weekly schedule created.");
  },

  async selectProfile(id) {
    if (!this.profiles[id]) return;
    this.activeId = id;
    await chrome.storage.local.set({ hq_active_schedule_profile: id });
    this._editingIndex = null;
    this.render();
  },

  addProfile() {
    this.openProfileEditor("add");
  },

  renameProfile() {
    if (!this.active) return;
    this.openProfileEditor("rename");
  },

  openProfileEditor(mode) {
    const form = document.getElementById("schedule-profile-editor");
    form.dataset.mode = mode;
    form.classList.remove("hidden");
    document.getElementById("schedule-profile-editor-label").textContent = mode === "rename" ? "Rename profile" : "New profile";
    document.getElementById("schedule-profile-name").value = mode === "rename" ? this.active?.name || "" : "";
    document.getElementById("schedule-profile-error").textContent = "";
    requestAnimationFrame(() => document.getElementById("schedule-profile-name").focus());
  },

  closeProfileEditor() {
    const form = document.getElementById("schedule-profile-editor");
    form.classList.add("hidden");
    form.reset();
    form.dataset.mode = "";
    document.getElementById("schedule-profile-error").textContent = "";
  },

  async saveProfileEditor() {
    const form = document.getElementById("schedule-profile-editor");
    const name = document.getElementById("schedule-profile-name").value.trim();
    if (!name) {
      document.getElementById("schedule-profile-error").textContent = "Choose a clear profile name.";
      return;
    }
    if (form.dataset.mode === "rename") {
      if (!this.active) return;
      this.active.name = name;
      await this.saveProfiles();
      this.renderProfileSelect();
      this.render();
      this.closeProfileEditor();
      return;
    }
    const id = "p" + Date.now().toString(36);
    this.profiles[id] = {
      name,
      days: { sun: [], mon: [], tue: [], wed: [], thu: [], fri: [], sat: [] },
      altDays: {},
      altLabel: "Alt week",
      altAnchorDate: null,
      altIntervalWeeks: 2,
      altWeekOverride: null,
    };
    await this.saveProfiles();
    await this.selectProfile(id);
    this.renderProfileSelect();
    this.closeProfileEditor();
  },

  async deleteProfile() {
    if (!this.active) return;
    const ids = Object.keys(this.profiles);
    if (ids.length <= 1) { Wallpaper?.toast?.("Can't delete the last remaining profile."); return; }
    if (!confirm(`Delete "${this.active.name}"? This can't be undone.`)) return;
    delete this.profiles[this.activeId];
    await this.saveProfiles();
    await this.selectProfile(Object.keys(this.profiles)[0]);
    this.renderProfileSelect();
  },

  async setWeekOverride(value) {
    if (!this.active) return;
    this.active.altWeekOverride = value === "auto" ? null : value === "alt";
    await this.saveProfiles();
    this.render();
  },

  toMinutes(value) {
    const [hours, minutes] = String(value || "00:00").split(":").map(Number);
    return hours * 60 + minutes;
  },

  fromMinutes(value) {
    const bounded = Math.max(0, Math.min(1439, Math.round(value)));
    return `${String(Math.floor(bounded / 60)).padStart(2, "0")}:${String(bounded % 60).padStart(2, "0")}`;
  },

  priorityScore(task, phase) {
    let score = task.priority === "high" ? 500 : task.priority === "medium" ? 240 : task.priority === "low" ? 20 : 90;
    if (task.dueAt) score += Math.max(0, 350 - Math.max(0, Number(task.dueAt) - Date.now()) / 3600000 * 8);
    score += Math.min(120, Math.max(0, (Date.now() - Number(task.created || Date.now())) / 86400000) * 8);
    const text = `${task.text || ""} ${task.venture || ""}`.toLowerCase();
    const phaseTerms = {
      wharton: ["wharton"], backlog: ["tuition", "client", "backlog"],
      trial: ["trial", "competition", "hackathon"], steady: ["competition", "math", "study", "school"],
    }[phase?.mode] || [];
    if (phaseTerms.some(term => text.includes(term))) score += 260;
    return score;
  },

  planningDate() {
    const today = new Date();
    const dayKey = SCHEDULE_DAY_KEYS[today.getDay()];
    const nowMinutes = today.getHours() * 60 + today.getMinutes();
    const futureFlex = this.blocksFor(this.active, dayKey, today).some(block => this.isFlexibleBlock(block) && this.toMinutes(block.e) > nowMinutes + 10);
    return futureFlex ? today : new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1);
  },

  async buildTaskPlan() {
    if (!this.active) return;
    const date = this.planningDate();
    const dayKey = SCHEDULE_DAY_KEYS[date.getDay()];
    const today = hqLocalDateKey(date) === hqLocalDateKey();
    const nowMinutes = new Date().getHours() * 60 + new Date().getMinutes();
    const phase = this.activePhase(this.active, date);
    const slots = this.blocksFor(this.active, dayKey, date)
      .filter(block => this.isFlexibleBlock(block) && (!today || this.toMinutes(block.e) > nowMinutes + 10))
      .map(block => ({ ...block, availableStart: today ? Math.max(this.toMinutes(block.s), nowMinutes + 5) : this.toMinutes(block.s), end: this.toMinutes(block.e) }))
      .filter(block => block.end - block.availableStart >= 10);
    const tasks = Tasks.data.filter(task => !task.done).sort((a, b) => this.priorityScore(b, phase) - this.priorityScore(a, phase));
    const draft = [];
    for (const slot of slots) {
      const task = tasks.find(candidate => !draft.some(entry => entry.taskId === candidate.id));
      if (!task) break;
      const duration = Math.min(Math.max(10, Number(task.estMinutes) || 25), slot.end - slot.availableStart);
      draft.push({
        id: crypto.randomUUID(), taskId: task.id, text: task.text,
        venture: task.venture || "Task", priority: task.priority || "normal",
        dateKey: hqLocalDateKey(date), s: this.fromMinutes(slot.availableStart), e: this.fromMinutes(slot.availableStart + duration),
        slot: slot.t, reason: `${task.priority ? `${task.priority} priority · ` : ""}${phase ? phase.label : "active timetable"}`,
      });
      if (draft.length >= 5) break;
    }
    this._planDraft = draft;
    await chrome.storage.local.set({ hq_schedule_plan_draft_v1: draft });
    this.renderTaskPlan(date);
  },

  chapterValues(chapters) {
    if (Array.isArray(chapters?.values) && chapters.values.length) {
      return [...new Set(chapters.values.map(Number).filter(Number.isFinite))].slice(0, 31);
    }
    if (!chapters || !Number.isFinite(Number(chapters.start)) || !Number.isFinite(Number(chapters.end))) return [];
    const start = Number(chapters.start);
    const end = Number(chapters.end);
    if (end < start) return [];
    return Array.from({ length:Math.min(31, end - start + 1) }, (_, index) => start + index);
  },

  async buildFocusedPlan({ title, subject, chapters, deadline, minutes = 25 } = {}) {
    if (!this.active) throw new Error("Choose a timetable profile before building a focus plan.");
    const cleanTitle = String(title || subject || "Focused study").replace(/\s+/g, " ").trim().slice(0, 160);
    const safeMinutes = Math.max(10, Math.min(180, Math.round(Number(minutes) || 25)));
    const start = new Date();
    start.setHours(12, 0, 0, 0);
    const finalDate = /^\d{4}-\d{2}-\d{2}$/.test(String(deadline || "")) ? new Date(`${deadline}T12:00:00`) : new Date(start);
    if (Number.isNaN(finalDate.getTime()) || finalDate < start) throw new Error("Choose a deadline from today onward.");
    const last = new Date(Math.min(finalDate.getTime(), start.getTime() + 21 * 86400000));
    const chapterValues = this.chapterValues(chapters);
    const chapterUnits = chapterValues.map(chapter => `${subject || "Study"} · Chapter ${chapter}`);
    const matchingTasks = (typeof Tasks !== "undefined" ? Tasks.data : [])
      .filter(task => !task.done && new RegExp(String(subject || "study").replace(/[^a-z0-9]+/gi, "|"), "i").test(`${task.text || ""} ${task.venture || ""}`))
      .slice(0, 8)
      .map(task => ({ label:task.text, taskId:task.id, priority:task.priority || "normal" }));
    const units = chapterUnits.length
      ? chapterUnits.map(label => ({ label, taskId:null, priority:"high" }))
      : matchingTasks.length
        ? matchingTasks
        : Array.from({ length:6 }, (_, index) => ({ label:`${cleanTitle} · session ${index + 1}`, taskId:null, priority:"high" }));
    const draft = [];
    let unitIndex = 0;
    for (let date = new Date(start); date <= last && draft.length < 10 && unitIndex < units.length; date = new Date(date.getFullYear(), date.getMonth(), date.getDate() + 1, 12)) {
      const dayKey = SCHEDULE_DAY_KEYS[date.getDay()];
      const isToday = hqLocalDateKey(date) === hqLocalDateKey();
      const nowMinutes = new Date().getHours() * 60 + new Date().getMinutes();
      const phase = this.activePhase(this.active, date);
      const slots = this.blocksFor(this.active, dayKey, date)
        .filter(block => this.isFlexibleBlock(block) && (!isToday || this.toMinutes(block.e) > nowMinutes + 10))
        .map(block => ({ ...block, availableStart:isToday ? Math.max(this.toMinutes(block.s), nowMinutes + 5) : this.toMinutes(block.s), end:this.toMinutes(block.e) }))
        .filter(block => block.end - block.availableStart >= 10);
      for (const slot of slots) {
        if (unitIndex >= units.length || draft.length >= 10) break;
        const unit = units[unitIndex++];
        const duration = Math.min(safeMinutes, slot.end - slot.availableStart);
        draft.push({
          id:crypto.randomUUID(), taskId:unit.taskId, text:unit.label, venture:subject || "Study", priority:unit.priority,
          dateKey:hqLocalDateKey(date), s:this.fromMinutes(slot.availableStart), e:this.fromMinutes(slot.availableStart + duration),
          slot:slot.t,
          reason:[`Nexus focus: ${cleanTitle}`, phase?.label, `deadline ${deadline}`].filter(Boolean).join(" · "),
        });
      }
    }
    this._planDraft = draft;
    await chrome.storage.local.set({ hq_schedule_plan_draft_v1:draft });
    this.renderTaskPlan(start);
    Wallpaper?.toast?.(draft.length ? `${draft.length} timetable block${draft.length === 1 ? "" : "s"} drafted. Open Schedule to review before applying.` : "No flexible timetable blocks were available before that deadline.");
    return draft;
  },

  renderTaskPlan(date = this._planDraft[0]?.dateKey ? new Date(`${this._planDraft[0].dateKey}T12:00:00`) : new Date()) {
    const panel = document.getElementById("schedule-smart-plan");
    const list = document.getElementById("schedule-smart-plan-preview");
    panel.classList.remove("hidden");
    if (!this._planDraft.length) {
      list.innerHTML = '<li class="empty-state">No safe fit found. Add open tasks with estimates or free a flexible timetable block.</li>';
      document.getElementById("schedule-apply-plan-btn").disabled = true;
      document.getElementById("schedule-plan-capacity").textContent = "0 blocks proposed";
      return;
    }
    document.getElementById("schedule-apply-plan-btn").disabled = false;
    const total = this._planDraft.reduce((sum, item) => sum + this.toMinutes(item.e) - this.toMinutes(item.s), 0);
    const dates = [...new Set(this._planDraft.map(item => item.dateKey))];
    const span = dates.length === 1
      ? this.fromPlanDate(dates[0])
      : `${this.fromPlanDate(dates[0])} → ${this.fromPlanDate(dates.at(-1))}`;
    document.getElementById("schedule-plan-capacity").textContent = `${span} · ${total} min · ${this._planDraft.length} blocks`;
    list.innerHTML = this._planDraft.map(item => `<li><span><b>${escapeHtml(this.fromPlanDate(item.dateKey))}</b>${escapeHtml(item.s)}–${escapeHtml(item.e)}</span><div><strong>${escapeHtml(item.text)}</strong><small>${escapeHtml(item.slot)} · ${escapeHtml(item.reason)}</small></div></li>`).join("");
  },

  fromPlanDate(dateKey) {
    const date = new Date(`${dateKey}T12:00:00`);
    return Number.isNaN(date.getTime()) ? String(dateKey || "") : date.toLocaleDateString([], { weekday:"short", month:"short", day:"numeric" });
  },

  async dismissTaskPlan() {
    this._planDraft = [];
    await chrome.storage.local.remove("hq_schedule_plan_draft_v1");
    document.getElementById("schedule-smart-plan").classList.add("hidden");
  },

  async applyTaskPlan() {
    if (!this._planDraft.length) return;
    const entries = this._planDraft.map(item => ({ dateKey: item.dateKey, text: `HQ plan ${item.s}–${item.e}: ${item.text}` }));
    const result = await CalendarRepository.addLegacyMany(entries);
    CalendarRepository.syncCalendar(result);
    if (result.inverse.length) await chrome.storage.local.set({ hq_schedule_plan_undo_v1: { inverse: result.inverse, createdAt: Date.now() } });
    else await chrome.storage.local.remove("hq_schedule_plan_undo_v1");
    document.getElementById("schedule-undo-plan-btn").disabled = !result.inverse.length;
    await Calendar.render();
    await Today?.render?.();
    Wallpaper?.toast?.(result.inverse.length ? `${result.inverse.length} reviewed task block${result.inverse.length === 1 ? "" : "s"} added to your calendar.` : "Those task blocks were already on the calendar; nothing was duplicated.");
    await this.dismissTaskPlan();
  },

  async undoTaskPlan() {
    const { hq_schedule_plan_undo_v1 } = await chrome.storage.local.get("hq_schedule_plan_undo_v1");
    if (!Array.isArray(hq_schedule_plan_undo_v1?.inverse)) return;
    const result = await CalendarRepository.undo(hq_schedule_plan_undo_v1.inverse);
    CalendarRepository.syncCalendar(result);
    await chrome.storage.local.remove("hq_schedule_plan_undo_v1");
    document.getElementById("schedule-undo-plan-btn").disabled = true;
    await Calendar.render();
    await Today?.render?.();
    Wallpaper?.toast?.("The applied timetable plan was undone.");
  },

  // --- Rendering: Today view ---

  render() {
    if (!this.active) {
      document.getElementById("schedule-today-heading").textContent = "No schedule profile";
      document.getElementById("schedule-today-list").innerHTML = '<li class="empty-state">Choose a first-run option above. Nothing has been imported yet.</li>';
      document.getElementById("schedule-day-tabs").innerHTML = "";
      document.getElementById("schedule-editor-list").innerHTML = '<li class="empty-state">Create a profile to add blocks.</li>';
      document.getElementById("schedule-week-override-row").classList.add("hidden");
      document.getElementById("schedule-editor-alt-toggle").classList.add("hidden");
      document.getElementById("schedule-phase-banner").textContent = "Create or sync a timetable to enable phase-aware planning.";
      if (typeof ContextBus !== "undefined") ContextBus.patch({ currentScheduleBlock: null });
      return;
    }
    this.renderTodayView();
    this.renderEditor();
    if (typeof Calendar !== "undefined" && Calendar._initPromise) void Calendar.render();
  },

  renderTodayView() {
    const profile = this.active;
    const phase = this.activePhase(profile);
    const todayKey = SCHEDULE_DAY_KEYS[new Date().getDay()];
    const alt = this.isAltWeek(profile);
    const blocks = this.blocksFor(profile, todayKey);

    document.getElementById("schedule-today-heading").textContent =
      `${SCHEDULE_DAY_LABELS[todayKey]}${this.dayHasAlt(profile, todayKey) ? (alt ? ` — ${profile.altLabel}` : " — regular") : ""}`;
    const phaseBanner = document.getElementById("schedule-phase-banner");
    if (phase) {
      phaseBanner.innerHTML = `<strong>${escapeHtml(phase.label)}</strong><span>${escapeHtml(phase.focus)}</span><small>${escapeHtml(phase.start)} → ${escapeHtml(phase.end)}</small>`;
      phaseBanner.dataset.phase = phase.id;
    } else if (profile.masterVersion === 8) {
      phaseBanner.innerHTML = '<strong>Master v8 timeline complete</strong><span>The dated competition plan ended on 4 December. Sync a newer timetable when your next phase is known.</span>';
      phaseBanner.dataset.phase = "complete";
    } else {
      phaseBanner.innerHTML = `<strong>${escapeHtml(profile.name)}</strong><span>Custom weekly profile · no dated phase overlay.</span>`;
      phaseBanner.dataset.phase = "custom";
    }

    const overrideSel = document.getElementById("schedule-week-override");
    overrideSel.value = profile.altWeekOverride === true ? "alt" : profile.altWeekOverride === false ? "regular" : "auto";
    document.getElementById("schedule-week-override-row").classList.toggle("hidden", !profile.altAnchorDate && !this.dayHasAlt(profile, todayKey) && !Object.keys(profile.altDays || {}).length);

    const list = document.getElementById("schedule-today-list");
    if (!blocks.length) {
      list.innerHTML = '<li class="empty-state">Nothing scheduled for today in this profile yet — add blocks in the editor below.</li>';
      return;
    }
    list.innerHTML = blocks.map((b, i) => `
      <li class="schedule-block" data-i="${i}">
        <span class="schedule-block-time">${b.s}–${b.e}</span>
        <span class="schedule-block-body"><strong>${escapeHtml(b.t)}</strong>${b.d ? `<br><span class="schedule-block-desc">${escapeHtml(b.d)}</span>` : ""}</span>
      </li>`).join("");
    this.renderTodayHighlightOnly();
  },

  // Cheap re-highlight of which block is "now" — called every minute
  // without touching anything else, so it never interrupts an in-progress
  // edit in the day editor below it.
  renderTodayHighlightOnly() {
    const profile = this.active;
    if (!profile) return;
    const todayKey = SCHEDULE_DAY_KEYS[new Date().getDay()];
    const blocks = this.blocksFor(profile, todayKey);
    const now = new Date();
    const nowMin = now.getHours() * 60 + now.getMinutes();
    const toMin = (hhmm) => { const [h, m] = hhmm.split(":").map(Number); return h * 60 + m; };

    document.querySelectorAll("#schedule-today-list .schedule-block").forEach((el) => {
      const b = blocks[parseInt(el.dataset.i)];
      if (!b) return;
      const start = toMin(b.s), end = toMin(b.e);
      el.classList.toggle("now", nowMin >= start && nowMin < end);
      el.classList.toggle("past", nowMin >= end);
    });

    if (typeof ContextBus !== "undefined") {
      const current = blocks.find(b => nowMin >= toMin(b.s) && nowMin < toMin(b.e));
      ContextBus.patch({ currentScheduleBlock: current ? current.t : null });
    }
  },

  // --- Rendering: day editor ---

  renderEditor() {
    const profile = this.active;
    const tabs = document.getElementById("schedule-day-tabs");
    tabs.innerHTML = SCHEDULE_DAY_KEYS.map(k =>
      `<button class="schedule-day-tab ${k === this._viewDay ? "active" : ""}" data-day="${k}">${SCHEDULE_DAY_LABELS[k].slice(0, 3)}</button>`
    ).join("");

    const dayKey = this._viewDay;
    const hasAlt = this.dayHasAlt(profile, dayKey);
    const altToggle = document.getElementById("schedule-editor-alt-toggle");
    altToggle.classList.toggle("hidden", !hasAlt);
    if (hasAlt) {
      altToggle.innerHTML = `
        <button class="schedule-alt-subtab ${!this._editingAlt ? "active" : ""}" data-alt="0">Regular</button>
        <button class="schedule-alt-subtab ${this._editingAlt ? "active" : ""}" data-alt="1">${escapeHtml(profile.altLabel || "Alt")}</button>`;
      altToggle.querySelectorAll("button").forEach(b => {
        b.onclick = () => { this._editingAlt = b.dataset.alt === "1"; this._editingIndex = null; this.renderEditor(); };
      });
    } else {
      this._editingAlt = false;
    }

    const blocks = (hasAlt && this._editingAlt) ? profile.altDays[dayKey] : profile.days[dayKey];
    const list = document.getElementById("schedule-editor-list");
    list.innerHTML = blocks.map((b, i) => {
      if (i === this._editingIndex) return this.editRowHtml(b, i);
      return `
        <li class="schedule-block" data-i="${i}">
          <span class="schedule-block-time">${b.s}–${b.e}</span>
          <span class="schedule-block-body"><strong>${escapeHtml(b.t)}</strong>${b.d ? `<br><span class="schedule-block-desc">${escapeHtml(b.d)}</span>` : ""}</span>
          <span class="schedule-block-actions">
            <button class="schedule-edit-btn" data-i="${i}" aria-label="Edit ${escapeAttribute(b.t)}">${Icons.span("file-text")}</button>
            <button class="schedule-del-btn" data-i="${i}" aria-label="Delete ${escapeAttribute(b.t)}">${Icons.span("x")}</button>
          </span>
        </li>`;
    }).join("") || '<li class="empty-state">No blocks on this day yet.</li>';

    list.querySelectorAll(".schedule-edit-btn").forEach(b => b.onclick = () => { this._editingIndex = parseInt(b.dataset.i); this.renderEditor(); });
    list.querySelectorAll(".schedule-del-btn").forEach(b => b.onclick = () => this.deleteBlock(parseInt(b.dataset.i)));
    list.querySelectorAll(".schedule-save-edit").forEach(b => b.onclick = () => this.saveEditBlock(parseInt(b.dataset.i)));
    list.querySelectorAll(".schedule-cancel-edit").forEach(b => b.onclick = () => { this._editingIndex = null; this.renderEditor(); });
  },

  editRowHtml(b, i) {
    return `
      <li class="schedule-block editing" data-i="${i}">
        <div class="schedule-edit-row">
          <input type="time" id="sched-edit-start-${i}" value="${b.s}">
          <input type="time" id="sched-edit-end-${i}" value="${b.e}">
          <input type="text" id="sched-edit-title-${i}" value="${escapeAttribute(b.t)}" placeholder="Title">
          <input type="text" id="sched-edit-desc-${i}" value="${escapeAttribute(b.d)}" placeholder="Note (optional)">
          <div class="schedule-edit-actions">
            <button class="schedule-save-edit" data-i="${i}">Save</button>
            <button class="schedule-cancel-edit">Cancel</button>
          </div>
        </div>
      </li>`;
  },

  currentDayArray() {
    const profile = this.active;
    const dayKey = this._viewDay;
    const hasAlt = this.dayHasAlt(profile, dayKey);
    return (hasAlt && this._editingAlt) ? profile.altDays[dayKey] : profile.days[dayKey];
  },

  sortDay(arr) {
    arr.sort((a, b) => a.s.localeCompare(b.s));
  },

  startAddBlock() {
    const arr = this.currentDayArray();
    arr.push({ s: "09:00", e: "09:30", t: "", d: "" });
    this._editingIndex = arr.length - 1;
    this.renderEditor();
  },

  async saveEditBlock(i) {
    const start = document.getElementById(`sched-edit-start-${i}`).value;
    const end = document.getElementById(`sched-edit-end-${i}`).value;
    const title = document.getElementById(`sched-edit-title-${i}`).value.trim();
    const desc = document.getElementById(`sched-edit-desc-${i}`).value.trim();
    if (!title) { Wallpaper?.toast?.("Give the block a title."); return; }
    if (!start || !end) { Wallpaper?.toast?.("Set both a start and end time."); return; }

    const arr = this.currentDayArray();
    arr[i] = { s: start, e: end, t: title, d: desc };
    this.sortDay(arr);
    this._editingIndex = null;
    await this.saveProfiles();
    this.render();
  },

  async deleteBlock(i) {
    const arr = this.currentDayArray();
    arr.splice(i, 1);
    this._editingIndex = null;
    await this.saveProfiles();
    this.render();
  },
};
